### ISSUE TITLE
[오류] users : logout 중, header 의 access token key 전달 이슈

### ISSUE THREAD

**Issue by mireu-san** [wanted-A/Team-A#15]
403 Error:Forbidden 발생중.

<img width="850" alt="image" src="https://github.com/wanted-A/Team-A/assets/67046863/cde05154-2534-4f01-90a4-afce2dc1737b">

해당 부분의 원인은 현재 획득한 header 를 통해, 전달이 안되는 것으로 보여집니다.
아래는 postman 의 화면입니다.
<img width="660" alt="image" src="https://github.com/wanted-A/Team-A/assets/67046863/21a3bece-dfdb-40c4-a71f-30109756318d">
<img width="650" alt="image" src="https://github.com/wanted-A/Team-A/assets/67046863/05513675-b7f7-4cb3-8e51-a779ec6706d6">

현재 디버깅 중에 있습니다.

**Comment by allen9535** [comment]
Swagger의 경우 혹시 Authorization이 아니라 X-CSRF Token을 통해 토큰이 전송되어 인증에 문제가 발생하는 것 같습니다.
Postman의 경우 쿼리 스트링으로 전송되고 있어서 문제가 발생하는 것 같고요.
혹시 다른 문제일 수도 있지만, 제 의견은 이렇습니다!

**Comment by ssu-uky** [comment]
코드를 첨부해주시면 코드를 보면서 같이 해결 해 나갈 수 있지 않을까요?

**Comment by mireu-san** [comment]
의견 주셔서 감사합니다.
하지만 제가 상황을 먼저 이해 하고 공유하는게 맞는 것 같아 조금 늦었습니다.
이제 [401 Unauthorized 로 의도된 에러](https://medium.com/django-rest/logout-django-rest-framework-eb1b53ac6d35)가 표시됩니다.
<img width="921" alt="image" src="https://github.com/wanted-A/Team-A/assets/67046863/c2b4a098-f5b7-48f4-89be-609caa779b18">

현재상황:
회원가입, 로그인, 로그아웃. jwt token 적용해서 작동 되는 것으로 1차 판단됩니다.

해당 이슈는 닫겠습니다. 내용은 정리되는데로 PR 때 요약해서 올리겠습니다. 감사합니다.
