### ISSUE TITLE
[제안] DB 사용 건에 대하여 제안드립니다.

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/Team-A#17]
현재 postgresql 로 개별로 db를 만들어서 사용하는걸로 알고 있는데,
일단 모델이나 기본적인 개발중에는 sqlite로 사용하고 더미데이터를 넣거나 배포할 때, db를 맞추는건 어떨까요?

**Comment by kyeon06** [comment]
네! 좋습니다!
로컬에서 테스트용으로 사용할 때만 sqlite를 사용하는게 더 좋겠네요

**Comment by mireu-san** [comment]
해외의 경우 [해당 접근법에 대해 부정적인 의견이 있습니다](https://www.quora.com/Is-it-bad-practice-to-use-SQLite-for-development-and-PostgreeSQL-for-production-when-building-Rails-apps).
<img width="518" alt="image" src="https://github.com/wanted-A/Team-A/assets/67046863/7ca3bd6d-5776-4e4e-9b06-352cdfa883ff">

[다만 1일 10만명 이상의 방문자가 유입되는 걸 상정하는 서비스가 아니라면 sqlite 로 가도 문제는 없다고 봅니다.](https://stackoverflow.com/questions/913067/sqlite-as-a-production-database-for-a-low-traffic-site)

**Comment by ssu-uky** [comment]
@mireu-san 

> 해외의 경우 [해당 접근법에 대해 부정적인 의견이 있습니다](https://www.quora.com/Is-it-bad-practice-to-use-SQLite-for-development-and-PostgreeSQL-for-production-when-building-Rails-apps).
> 
> <img width="518" alt="image" src="https://github.com/wanted-A/Team-A/assets/67046863/7ca3bd6d-5776-4e4e-9b06-352cdfa883ff">
> 
> 
> 
> [다만 1일 10만명 이상의 방문자가 유입되는 걸 상정하는 서비스가 아니라면 sqlite 로 가도 문제는 없다고 봅니다.](https://stackoverflow.com/questions/913067/sqlite-as-a-production-database-for-a-low-traffic-site)
> 
> 

- [ ] 개발중일때에는 10만명이상의 방문자가 유입이 되지 않을거라고 생각합니다. 더미데이터를 넣을 때도 10만명보다는 적게 넣을테니 .. 모델이 다 완성되고 어느정도 구현이 된 다음에 데이터베이스를 변경해도 무방하다고 생각합니다 :)

**Comment by allen9535** [comment]
@mireu-san 의견은 잘 보았습니다!
하지만 저는 개발 단계에서의 SQLite 사용에 찬성합니다.
저희는 현재 DB와 통신할 때 Django ORM을 사용중이며, 이는 편리함 때문이기도 하지만 DB에 대한 종속성을 줄인다는 측면 또한 있을 것입니다.
DB에 대한 종속성을 줄인다는 것은 결국 저희가 Python 코드만 작성하면 DB에 데이터가 어떤 방식으로 저장되게 할 것인지는 Django가 결정할 문제라는 뜻이기도 하다는 것이 저의 생각입니다.

다만, 모두 같은 데이터를 사용해 개발을 진행하고 싶다면, 하나의 PostgreSQL DB를 만들고 이를 모두가 활용하는 방법은 괜찮다고 생각합니다!
결국 논점은 SQLite를 사용할 것이냐 PostgreSQL DB를 사용할 것이냐가 아니라, 모든 팀원이 하나의 DB에서 통일된 형식의 데이터를 사용해 테스트할 것이냐 아니면 각자 알아서 데이터를 만들고 테스트할 것이냐일 것이라고 생각합니다.
해당 논점에서라면, 저희가 공수를 조금 더 들여서 한 개의 통합된 DB를 만들고 관리하느니 그냥 각자 자신의 로컬 PC에서 테스트하는 것이 편리하다고 생각하는 것이죠!

**Comment by kyeon06** [comment]
> 결국 논점은 SQLite를 사용할 것이냐 PostgreSQL DB를 사용할 것이냐가 아니라, 모든 팀원이 하나의 DB에서 통일된 형식의 데이터를 사용해 테스트할 것이냐 아니면 각자 알아서 데이터를 만들고 테스트할 것이냐일 것이라고 생각합니다.
> 해당 논점에서라면, 저희가 공수를 조금 더 들여서 한 개의 통합된 DB를 만들고 관리하느니 그냥 각자 자신의 로컬 PC에서 테스트하는 것이 편리하다고 생각하는 것이죠!

저도 이 의견에 동의하는 바입니다!

**Comment by mireu-san** [comment]
네, 그럼 저도 이번 프로젝트에서는 sqlite 로 진행하겠습니다.
```
# 아래와 같이 변경했습니다.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
```
