### ISSUE TITLE
[오류] User Model 오류 발견 - #4

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/Team-A#8]
## 오류 메세지
```py
...
self.UserModel._default_manager.db_manager(database).create_superuser
File in create_superuser
    return self.create_user(email, password, **extra_fields)
File in create_user
    user = self.model(email=email, **extra_fields)
TypeError: User() got unexpected keyword arguments: 'is_staff'
```

---
### #4 User Model 필드 

`python manage.py createsuperuser` 할 때 오류가 나고, admin 사이트에서 오류가 납니다.

---

## 제안
```py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class User(AbstractBaseUser,PermissionsMixin): # PermissionsMixin 추가

...
is_staff = models.BooleanField(default=False) # 추가
is_superuser = models.BooleanField(default=False) # 추가
...

```
PermissionsMixin을 추가해서 User에 상속받게 한 후,
User 모델에 `is_staff` 와 is_superuser 를 넣으면 오류가 해결됩니다.
확인 부탁드립니다 :)

---
## 추가 요청 사항
현재 비밀번호 해쉬화가 되지 않고 있는걸로 확인됩니다.
확인 후 수정 부탁드리겠습니다.

**Comment by mireu-san** [comment]
제보 감사합니다. 테스트로 인지 했으며, 제안에 맞게 PermissionsMixin 으로 해당 부분을 적용하였습니다.

**Comment by mireu-san** [comment]
비밀번호 해쉬화 부분 로직의 점검을 마쳤습니다.
users 의 로직에서 비밀번호 해싱은 되고 있는 것으로 확인되었습니다.
해당 해싱 미처리 이슈 부분을 어떻게 재현 하신건지 알 수 있을까요? 
아쉽게도, 현재 제 시점에서는 해싱이 안되는 문제를 발견 할 수 없었습니다...
(추신: 이해했습니다. 이건 어제 오후 6시 경 commit 기준으로 말씀하셨던 거군요. 이 부분은 어제 저녁에 해결했습니다.)

**Comment by mireu-san** [comment]
현재 알려주신 이슈 들은 해결 된 것으로 보고, 다시 PR 을 develop 로 보내겠습니다.

**Comment by mireu-san** [comment]
(이슈 종료)
